services:

  kokoro-fastapi-cpu:
    ports:
      - 8880:8880
    image: ghcr.io/remsky/kokoro-fastapi-cpu
    restart: always

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    tty: true
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      ollama:
        condition: service_started
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'NODE_OPTIONS=--max-old-space-size=8192'
    restart: unless-stopped

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    volumes:
      - pipelines:/app/pipelines
    restart: always
    depends_on:
      - ollama 
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PIPELINES_API_KEY=0p3n-w3bu!

  open-webui-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: open-webui-frontend
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./static:/app/static
    ports:
      - "2705:5173"
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
    restart: unless-stopped

volumes:
  open-webui: {}
  pipelines: {}