FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

# Para produção
RUN npm run build
EXPOSE 2705
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]

